# Generated by Django 4.1 on 2023-12-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                ("cookie", models.CharField(max_length=1000)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField(auto_now=True)),
                ("end_time", models.DateTimeField(auto_now=True)),
                ("password", models.CharField(max_length=1000)),
                ("name", models.CharField(max_length=1000)),
                ("email", models.CharField(max_length=1000)),
                ("superuser", models.CharField(default="普通用户", max_length=1000)),
                ("money_left", models.FloatField(default=5.0)),
            ],
        ),
        migrations.CreateModel(
            name="chat_history",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("generar_time", models.DateTimeField(auto_now=True)),
                ("content1", models.CharField(default="", max_length=1500)),
                ("content2", models.CharField(default="", max_length=1500)),
                ("content3", models.CharField(default="", max_length=1500)),
                ("timeofcontent1", models.DateTimeField(auto_now=True)),
                ("timeofcontent2", models.DateTimeField(auto_now=True)),
                ("timeofcontent3", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sqlchat.user"
                    ),
                ),
            ],
        ),
    ]
